#!/bin/sh
tests_root="$(dirname "$0")"
program="$tests_root/../index.js"
pass_symbol="😊 [32mPASS"
fail_symbol="😭 [31mFAIL"
exit_code=0

# a little helper so people can get verbose output with `-v`
if [ "$1" = "-v" ]; then
	exec 3>&2
else
	if ! { true >&3; } 2> /dev/null; then
		exec 3>/dev/null
	fi
fi

if ! { true >&4; } 2> /dev/null; then
	exec 4>/dev/null
fi

for baddy in "$tests_root"/bad/*; do
	name="$(basename $baddy)"
	# redirect errors to the fourth file descriptor so users can turn it on with
	# ./test 4>&2
	if { "$program" "$baddy"; } 1>/dev/null 2>&4; then
		>&2 echo "$fail_symbol bad origami.json '$name' seemed good"
		exit_code=1
	else
		>&2 echo "$pass_symbol bad origami.json '$name' seemed bad"
	fi
done

for goody in "$tests_root"/good/*; do
	name="$(basename $goody)"
	# redirect errors to the third file descriptor so users can turn it on
	# with ./test 3>&2
	if { "$program" "$goody"; } 1>/dev/null 2>&3; then
		>&2 echo "$pass_symbol good origami.json '$name' seemed good"
	else
		>&2 echo "$fail_symbol good origami.json '$name' seemed bad"
		exit_code=1
	fi
done

exit $exit_code
