#!/bin/sh
name="$1"
cat > ./src/rules/"$name.ts" <<EOF
import type {Rule} from "../lib/rule"
import {FieldType} from "../lib/field"
import * as skips from "../lib/skip"

let rules: Rule[] = [
	{
		rule: "",
		skip: skips.unlessClippy,
		test: value => {
			 // return true if it passes, false if it fails
			 return true || false
		},
	},
]

export default {
	type: FieldType.Direct,
	rules
}
EOF
