#!/bin/sh
name="$1"
cat > ./src/rules/"$name.ts" <<EOF
import type {Rule} from "../lib/rule"
import * as skips from "../lib/skips"

let rules: Rule[] = [
	{
		rule: "",
		skip: skips.unlessClippy,
		test: value => {
			 // return true if it passes, false if it fails
			 return true || false
		},
	},
]

export default rules
EOF
